### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by buttermiilk** [freetnt5852/LadyBug-Bot#18]
After running ```node index.js``` this occurs:

```Loaded 161 commands.
Loaded 11 events.
(node:2432) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:2432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ravener** [comment]
PostgreSQL is not running on port 5432. The bot heavily relies on the database so setup a PostgreSQL instance and configure accordingly in config.json although if you decided to use a different port you will need to change the code slightly as it does not account into port changes and assumes port 5432

**Comment by buttermiilk** [comment]
After fixing 
```
UnhandledPromiseRejectionWarning: Error: 401 Unauthorized
    at IncomingMessage.<anonymous> (C:\miyako\node_modules\dblapi.js\src\index.js:118:25)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:6284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ravener** [comment]
Is your bot in DBL (https://top.gg) the bot tries to post DBL stats and needs an api token. You can temporarily comment out the `this.dbl =...` stuff in `structures/MiyakoClient.js`

**Comment by buttermiilk** [comment]
Ah, handled. Thanks for the help
