### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by A0Zv27fzsN** [freetnt5852/LadyBug-Bot#22]
```
TypeError: require(...) is not a constructor
    at Map.load (C:\Users\aa\Desktop\bot\structures\Store.js:31:28)
    at map (C:\Users\aa\Desktop\bot\structures\Store.js:48:42)
    at Array.map (<anonymous>)
    at Map.loadFiles (C:\Users\aa\Desktop\bot\structures\Store.js:48:23)
```

**Comment by ravener** [comment]
Did you add any new commands/events? That error is most likely forgetting `module.exports`

**Comment by ravener** [comment]
Closing due to inactivity
